# Site settings
title: 崔仪洁的博客
email: cyj976655@gmail.com
description: > 
崔仪洁的博客，记录生活的点点滴滴。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cc976655.github.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
github:   cc976655
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: cuje


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
