auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: "崔仪洁的博客"
title: 崔仪洁的博客
description: 念念不忘，必有回响。
url: https://cc976655.github.io/
feed: /atom.xml
author_info: <a href="https://cc976655.github.io/">Cui Yijie</a>
